global:
  resolve_timeout: 5m

route:
  receiver: "default"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

# receivers:
#   - name: "default"
#     email_configs:
#       - to: "adharbattulwar24@gmail.com"
#         from: "subnex@adharbattulwar.com"
#         smarthost: smtp.gmail.com:587
#         auth_username: "adharbattulwar24@gmail.com"
#         auth_password: "wigbzhjxwsljhdot"