groups:
  - name: service-health-alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service down"
          description: "Service {{ $labels.job }} is DOWN."

  - name: cpu-memory-alerts
    rules:
      - alert: HighCPUUsage
        expr: rate(node_cpu_seconds_total{mode!="idle"}[2m]) > 0.80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 2 minutes."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85%."

  # - name: disk-alerts
  #   rules:
  #     - alert: DiskAlmostFull
  #       expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.15
  #       for: 1m
  #       labels:
  #         severity: critical
  #       annotations:
  #         summary: "Disk almost full"
  #         description: "Disk space is below 15%."

  - name: http-error-alerts
    rules:
      - alert: High5xxErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate"
          description: "High rate of HTTP 5xx errors detected."

  - name: payment-alerts
    rules:
      - alert: PaymentServiceDown
        expr: up{job="payment-service"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Payment service down"
          description: "Payment service is unreachable."
  
  - name: container-alerts
    rules:
      - alert: ContainerHighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Container memory high"
          description: "Container {{ $labels.name }} memory usage > 90%."

