global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "auth-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8083"]

  - job_name: "subscription-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["subscription-service:8082"]

  - job_name: "payment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8085"]

  - job_name: "email-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["email-service:8084"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
      
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

